Initial HTML
jdo697/student-grade-table pull request #1
Opened 2020-11-20 04:41 UTC by jdo697

![image](https://user-images.githubusercontent.com/67031107/99759627-a5882480-2aa7-11eb-88a0-6a4f208ec93c.png)

2020-11-20 20:27 UTC, TimelikeClosure requested changes

2020-11-20 20:27 UTC, TimelikeClosure commented on components/app.js
> +  },
In the `constructor`, the `handleGetGradesError` and `handleGetGradesSuccess` methods need to be bound, not called: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Function/bind#Syntax

2020-11-20 20:27 UTC, TimelikeClosure commented on components/app.js
> +    .success(this.handleGetGradesSuccess())
The `handleGetGradesError` and `handleGetGradesSuccess` methods shouldn't be called here. Those methods _should_ be passed to the `error` / `success` methods to be called later, but you shouldn't call them directly.

2020-11-21 16:41 UTC, jdo697 commented
![image](https://user-images.githubusercontent.com/67031107/99882445-6657f180-2bd5-11eb-8778-bf97b1c5e60f.png)

2020-11-21 18:00 UTC, TimelikeClosure approved these changes

2020-11-21 18:05 UTC, merged